### ISSUE TITLE
Can't get the plugin to generate even one line of output, though it creates the output folder

### ISSUE THREAD

**Issue by peterturquoise** [bobbingwide/oik-bwtrace#101]
I followed the docs and installed oik-trace into WP (running as an Azure App)> The directory I ask it to create and set up int he plugin's "trace files" form appears but despite filling in as many other forms and tick boxes as are available it will not generate even one single character of output.

What could be wrong? Do I have to set something in wp-config.php despite the docs saying I don't have to ? I would have though that it would create _something_ other than the output folder....I have it set to "Verbose level - noisier than debug" but nope - not a thing. I have all the fields set...

![image](https://user-images.githubusercontent.com/12343560/115480842-42134600-a243-11eb-83db-de52ec109b06.png)
![image](https://user-images.githubusercontent.com/12343560/115480854-48a1bd80-a243-11eb-9122-155022f048d3.png)
![image](https://user-images.githubusercontent.com/12343560/115480861-4f303500-a243-11eb-8946-8b0bc6fa17c8.png)

Any ideas ? I'm sure it must be something obvious....

**Comment by bobbingwide** [comment]
Sorry, only just seen this. I believe the workaround is to remove the leading space before `C:/` in the trace files directory.

**Comment by bobbingwide** [comment]
I've developed a fix for this.

**Comment by bobbingwide** [comment]
Released in v3.2.2. Closing therefore.
