### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by orangutangle** [bobbingwide/oik-bwtrace#70]
Fatal error: Uncaught Error: Call to undefined function gob() in /wp-content/plugins/oik-bwtrace/includes/class-BW-trace-controller.php:146

I searched the repository and there doesn't seem to be a definition for the gob function. Am I missing dependency?

**Comment by bobbingwide** [comment]
Hi Robin, , `gob()` stands for Go bang. It's a function that's not meant to exist. It's a bug.
You've probably got a define in your wp-config.php file
```
define( 'BW_TRACE_ON', true );
```
Comment that out or the line in error.

**Comment by bobbingwide** [comment]
I've removed the `gob()` that was causing the problem.
It was commented out a while back.

**Comment by bobbingwide** [comment]
Even though there's still one uncommented `gob()` I'm going to close this issue.
